#!/bin/sh
set -eu

API_BASE_URL_VALUE="${FRONTEND_API_BASE_URL:-/api}"
CRM_API_BASE_URL_VALUE="${FRONTEND_CRM_API_BASE_URL:-/crm-api}"
APP_ENV_VALUE="${FRONTEND_APP_ENV:-production}"
FEATURE_ADMIN_ENTERPRISE_REDESIGN_VALUE="${FRONTEND_FEATURE_ADMIN_ENTERPRISE_REDESIGN:-false}"
FEATURE_ADMIN_KNOWLEDGE_BASE_ENTERPRISE_VALUE="${FRONTEND_FEATURE_ADMIN_KNOWLEDGE_BASE_ENTERPRISE:-false}"

escape_js() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

API_BASE_URL_ESCAPED="$(escape_js "$API_BASE_URL_VALUE")"
CRM_API_BASE_URL_ESCAPED="$(escape_js "$CRM_API_BASE_URL_VALUE")"
APP_ENV_ESCAPED="$(escape_js "$APP_ENV_VALUE")"
FEATURE_ADMIN_ENTERPRISE_REDESIGN_ESCAPED="$(escape_js "$FEATURE_ADMIN_ENTERPRISE_REDESIGN_VALUE")"
FEATURE_ADMIN_KNOWLEDGE_BASE_ENTERPRISE_ESCAPED="$(escape_js "$FEATURE_ADMIN_KNOWLEDGE_BASE_ENTERPRISE_VALUE")"

cat > /usr/share/nginx/html/runtime-config.js <<EOF
window.__RUNTIME_CONFIG__ = {
  API_BASE_URL: "${API_BASE_URL_ESCAPED}",
  CRM_API_BASE_URL: "${CRM_API_BASE_URL_ESCAPED}",
  APP_ENV: "${APP_ENV_ESCAPED}",
  FEATURE_ADMIN_ENTERPRISE_REDESIGN: "${FEATURE_ADMIN_ENTERPRISE_REDESIGN_ESCAPED}",
  FEATURE_ADMIN_KNOWLEDGE_BASE_ENTERPRISE: "${FEATURE_ADMIN_KNOWLEDGE_BASE_ENTERPRISE_ESCAPED}"
};
EOF
