import type { EndpointDef, HttpMethod } from '../types/api'

export const ENDPOINTS: EndpointDef[] = [
  {
    id: 'health_main',
    category: 'Health',
    name: 'Service Health',
    description: 'Basic service health status',
    method: 'GET',
    path: '/health',
    kind: 'http',
    bodyMode: 'none',
  },
  {
    id: 'health_live',
    category: 'Health',
    name: 'Liveness Probe',
    description: 'Process liveness check',
    method: 'GET',
    path: '/health/live',
    kind: 'http',
    bodyMode: 'none',
  },
  {
    id: 'health_ready',
    category: 'Health',
    name: 'Readiness Probe',
    description: 'Dependency readiness check',
    method: 'GET',
    path: '/health/ready',
    kind: 'http',
    bodyMode: 'none',
  },
  {
    id: 'health_metrics',
    category: 'Health',
    name: 'Prometheus Metrics',
    description: 'Raw metrics endpoint',
    method: 'GET',
    path: '/metrics',
    kind: 'http',
    bodyMode: 'none',
  },

  {
    id: 'agent_query',
    category: 'Agent',
    name: 'Agent Query',
    description: 'Synchronous agent response',
    method: 'POST',
    path: '/agent/query',
    kind: 'http',
    bodyMode: 'json',
    defaultBody: {
      session_id: 'session_demo',
      question: 'Summarize available customer support options.',
    },
  },
  {
    id: 'agent_stream',
    category: 'Agent',
    name: 'Agent Stream',
    description: 'SSE stream with reasoning/tool/token/cost events',
    method: 'POST',
    path: '/agent/stream',
    kind: 'sse',
    bodyMode: 'json',
    defaultBody: {
      session_id: 'session_demo',
      question: 'Explain loan foreclosure charges with examples.',
    },
  },
  {
    id: 'follow_up',
    category: 'Agent',
    name: 'Follow-up Generator',
    description: 'Generate follow-up questions',
    method: 'POST',
    path: '/agent/follow-up',
    kind: 'http',
    bodyMode: 'json',
    defaultBody: {
      session_id: 'session_demo',
      question: 'What should I do next for EMI reduction?',
    },
  },
  {
    id: 'follow_up_stream',
    category: 'Agent',
    name: 'Follow-up Stream',
    description: 'SSE follow-up question generation stream',
    method: 'POST',
    path: '/agent/follow-up-stream',
    kind: 'sse',
    bodyMode: 'json',
    defaultBody: {
      session_id: 'session_demo',
      question: 'Help me with repayment planning.',
    },
  },

  {
    id: 'sessions_list',
    category: 'Sessions',
    name: 'List Sessions',
    description: 'List active sessions',
    method: 'GET',
    path: '/agent/sessions',
    kind: 'http',
    bodyMode: 'none',
  },
  {
    id: 'sessions_verify',
    category: 'Sessions',
    name: 'Verify Session',
    description: 'Validate session existence',
    method: 'GET',
    path: '/agent/verify/{session_id}',
    kind: 'http',
    bodyMode: 'none',
    defaultPathParams: { session_id: 'session_demo' },
  },
  {
    id: 'sessions_get_config',
    category: 'Sessions',
    name: 'Get Session Config',
    description: 'Read effective session configuration',
    method: 'GET',
    path: '/agent/config/{session_id}',
    kind: 'http',
    bodyMode: 'none',
    defaultPathParams: { session_id: 'session_demo' },
  },
  {
    id: 'sessions_set_config',
    category: 'Sessions',
    name: 'Set Session Config',
    description: 'Create/update session configuration',
    method: 'POST',
    path: '/agent/config',
    kind: 'http',
    bodyMode: 'json',
    defaultBody: {
      session_id: 'session_demo',
      model_name: 'z-ai/glm-5',
      provider: 'openrouter',
      reasoning_effort: 'high',
      system_prompt: 'You are a precise financial assistant.',
    },
  },
  {
    id: 'sessions_logout',
    category: 'Sessions',
    name: 'Logout Session',
    description: 'Delete session state/config',
    method: 'DELETE',
    path: '/agent/logout/{session_id}',
    kind: 'http',
    bodyMode: 'none',
    defaultPathParams: { session_id: 'session_demo' },
  },
  {
    id: 'sessions_cost',
    category: 'Sessions',
    name: 'Session Cost',
    description: 'Aggregated usage and cost for a session',
    method: 'GET',
    path: '/agent/sessions/{session_id}/cost',
    kind: 'http',
    bodyMode: 'none',
    defaultPathParams: { session_id: 'session_demo' },
  },
  {
    id: 'sessions_cost_history',
    category: 'Sessions',
    name: 'Session Cost History',
    description: 'Chronological cost history entries',
    method: 'GET',
    path: '/agent/sessions/{session_id}/cost/history',
    kind: 'http',
    bodyMode: 'none',
    defaultPathParams: { session_id: 'session_demo' },
    defaultQuery: { limit: 100 },
  },
  {
    id: 'sessions_cost_reset',
    category: 'Sessions',
    name: 'Reset Session Cost',
    description: 'Reset cost tracker for a session',
    method: 'DELETE',
    path: '/agent/sessions/{session_id}/cost',
    kind: 'http',
    bodyMode: 'none',
    defaultPathParams: { session_id: 'session_demo' },
  },
  {
    id: 'sessions_summary',
    category: 'Sessions',
    name: 'Sessions Cost Summary',
    description: 'Global session cost summary',
    method: 'GET',
    path: '/agent/sessions/summary',
    kind: 'http',
    bodyMode: 'none',
  },
  {
    id: 'sessions_cleanup',
    category: 'Sessions',
    name: 'Cleanup Cost Keys',
    description: 'Admin cleanup for corrupted cost keys',
    method: 'DELETE',
    path: '/agent/sessions/cleanup',
    kind: 'http',
    bodyMode: 'none',
  },

  {
    id: 'models_list',
    category: 'Models',
    name: 'Model Catalog',
    description: 'Available model listing',
    method: 'GET',
    path: '/agent/models',
    kind: 'http',
    bodyMode: 'none',
  },

  {
    id: 'router_classify',
    category: 'Router',
    name: 'Router Classify',
    description: 'Classify query with NBFC router',
    method: 'POST',
    path: '/agent/router/classify',
    kind: 'http',
    bodyMode: 'json',
    defaultBody: {
      session_id: 'session_demo',
      text: 'I missed EMI due date, what next?',
      mode: 'hybrid',
    },
  },
  {
    id: 'router_compare',
    category: 'Router',
    name: 'Router Compare',
    description: 'Compare router output paths',
    method: 'POST',
    path: '/agent/router/compare',
    kind: 'http',
    bodyMode: 'json',
    defaultBody: {
      session_id: 'session_demo',
      text: 'How do I check foreclosure amount?',
      mode: 'compare',
    },
  },

  {
    id: 'admin_followups',
    category: 'Admin',
    name: 'All Follow-ups',
    description: 'Fetch cached follow-up sets',
    method: 'GET',
    path: '/agent/all-follow-ups',
    kind: 'http',
    bodyMode: 'none',
  },
  {
    id: 'admin_faq_batch',
    category: 'Admin',
    name: 'FAQ Batch Ingest',
    description: 'Stream ingest from JSON FAQ list',
    method: 'POST',
    path: '/agent/admin/faqs/batch-json',
    kind: 'sse',
    bodyMode: 'json',
    defaultHeaders: {
      'X-Admin-Key': '',
      'X-OpenRouter-Key': '',
      'X-Groq-Key': '',
    },
    defaultBody: {
      items: [
        {
          question: 'What is foreclosure?',
          answer: 'Foreclosure is early closure of a loan account before tenure end.',
        },
      ],
    },
  },
  {
    id: 'admin_faq_pdf',
    category: 'Admin',
    name: 'FAQ PDF Upload',
    description: 'Stream ingest from PDF upload',
    method: 'POST',
    path: '/agent/admin/faqs/upload-pdf',
    kind: 'sse',
    bodyMode: 'multipart',
    defaultHeaders: {
      'X-Admin-Key': '',
      'X-OpenRouter-Key': '',
      'X-Groq-Key': '',
    },
  },
  {
    id: 'admin_faq_get',
    category: 'Admin',
    name: 'List FAQs',
    description: 'Paginated FAQ retrieval',
    method: 'GET',
    path: '/agent/admin/faqs',
    kind: 'http',
    bodyMode: 'none',
    defaultQuery: { limit: 100, skip: 0 },
  },
  {
    id: 'admin_faq_edit',
    category: 'Admin',
    name: 'Edit FAQ',
    description: 'Update existing FAQ question/answer',
    method: 'PUT',
    path: '/agent/admin/faqs',
    kind: 'http',
    bodyMode: 'json',
    defaultHeaders: {
      'X-Admin-Key': '',
      'X-OpenRouter-Key': '',
    },
    defaultBody: {
      original_question: 'What is foreclosure?',
      new_question: 'What is loan foreclosure?',
      new_answer: 'Foreclosure means pre-closing loan before tenure completion.',
    },
  },
  {
    id: 'admin_faq_delete',
    category: 'Admin',
    name: 'Delete FAQ by Question',
    description: 'Delete FAQ by exact question string',
    method: 'DELETE',
    path: '/agent/admin/faqs',
    kind: 'http',
    bodyMode: 'none',
    defaultHeaders: { 'X-Admin-Key': '' },
    defaultQuery: { question: 'What is loan foreclosure?' },
  },
  {
    id: 'admin_faq_delete_all',
    category: 'Admin',
    name: 'Delete All FAQs',
    description: 'Clear complete FAQ corpus',
    method: 'DELETE',
    path: '/agent/admin/faqs/all',
    kind: 'http',
    bodyMode: 'none',
    defaultHeaders: { 'X-Admin-Key': '' },
  },
  {
    id: 'admin_faq_semantic_search',
    category: 'Admin',
    name: 'FAQ Semantic Search',
    description: 'Semantic search over FAQ corpus',
    method: 'POST',
    path: '/agent/admin/faqs/semantic-search',
    kind: 'http',
    bodyMode: 'json',
    defaultHeaders: { 'X-OpenRouter-Key': '' },
    defaultBody: { query: 'foreclosure charges', limit: 5 },
  },
  {
    id: 'admin_faq_semantic_delete',
    category: 'Admin',
    name: 'FAQ Semantic Delete',
    description: 'Delete FAQ by vector proximity',
    method: 'POST',
    path: '/agent/admin/faqs/semantic-delete',
    kind: 'http',
    bodyMode: 'json',
    defaultHeaders: {
      'X-Admin-Key': '',
      'X-OpenRouter-Key': '',
    },
    defaultBody: { query: 'foreclosure', threshold: 0.92 },
  },

  {
    id: 'eval_ingest',
    category: 'Evaluation',
    name: 'Eval Ingest',
    description: 'Ingest traces, events, and evals',
    method: 'POST',
    path: '/eval/ingest',
    kind: 'http',
    bodyMode: 'json',
    defaultHeaders: { 'X-Eval-Ingest-Key': '' },
    defaultBody: {
      trace: {
        trace_id: 'trace_demo_001',
        status: 'completed',
        provider: 'openrouter',
        model: 'z-ai/glm-5',
        endpoint: '/agent/query',
        session_id: 'session_demo',
        case_id: 'case_demo',
      },
      events: [
        {
          trace_id: 'trace_demo_001',
          seq: 1,
          event_type: 'token',
          name: 'token',
          text: 'hello',
          payload: {},
          meta: {},
        },
      ],
      evals: [
        {
          eval_id: 'eval_demo_001',
          trace_id: 'trace_demo_001',
          metric_name: 'accuracy',
          score: 0.9,
          passed: true,
          reasoning: 'correct',
          evaluator_id: 'judge_demo',
          evidence: [],
          meta: {},
        },
      ],
    },
  },
  {
    id: 'eval_search',
    category: 'Evaluation',
    name: 'Eval Search',
    description: 'Filter/search evaluation traces',
    method: 'GET',
    path: '/eval/search',
    kind: 'http',
    bodyMode: 'none',
    defaultQuery: { limit: 50, offset: 0, order: 'desc' },
  },
  {
    id: 'eval_sessions',
    category: 'Evaluation',
    name: 'Eval Sessions',
    description: 'List sessions with evaluation traces',
    method: 'GET',
    path: '/eval/sessions',
    kind: 'http',
    bodyMode: 'none',
    defaultQuery: { limit: 25, offset: 0 },
  },
  {
    id: 'eval_trace',
    category: 'Evaluation',
    name: 'Eval Trace Detail',
    description: 'Detailed trace by trace_id',
    method: 'GET',
    path: '/eval/trace/{trace_id}',
    kind: 'http',
    bodyMode: 'none',
    defaultPathParams: { trace_id: 'trace_demo_001' },
  },
  {
    id: 'eval_fulltext',
    category: 'Evaluation',
    name: 'Eval Fulltext Search',
    description: 'Fulltext search for trace/event/result indexes',
    method: 'GET',
    path: '/eval/fulltext',
    kind: 'http',
    bodyMode: 'none',
    defaultQuery: {
      q: 'foreclosure',
      kind: 'event',
      limit: 50,
      offset: 0,
    },
  },
  {
    id: 'eval_vector_search',
    category: 'Evaluation',
    name: 'Eval Vector Search',
    description: 'Vector search over trace/result embeddings',
    method: 'POST',
    path: '/eval/vector-search',
    kind: 'http',
    bodyMode: 'json',
    defaultHeaders: { 'X-OpenRouter-Key': '' },
    defaultBody: {
      kind: 'trace',
      text: 'foreclosure process',
      k: 10,
      min_score: 0,
    },
  },
  {
    id: 'eval_metrics_summary',
    category: 'Evaluation',
    name: 'Eval Metrics Summary',
    description: 'Aggregated metrics and pass rates',
    method: 'GET',
    path: '/eval/metrics/summary',
    kind: 'http',
    bodyMode: 'none',
  },
  {
    id: 'eval_metrics_failures',
    category: 'Evaluation',
    name: 'Eval Metric Failures',
    description: 'Failure-focused metric listing',
    method: 'GET',
    path: '/eval/metrics/failures',
    kind: 'http',
    bodyMode: 'none',
    defaultQuery: { limit: 50, offset: 0 },
  },
  {
    id: 'eval_question_types',
    category: 'Evaluation',
    name: 'Eval Question Types',
    description: 'Question type distribution from eval traces',
    method: 'GET',
    path: '/eval/question-types',
    kind: 'http',
    bodyMode: 'none',
    defaultQuery: { limit: 200 },
  },

  {
    id: 'rate_limit_metrics',
    category: 'Rate Limiting',
    name: 'Rate Limit Metrics',
    description: 'Limiter metrics across all limiters',
    method: 'GET',
    path: '/rate-limit/metrics',
    kind: 'http',
    bodyMode: 'none',
  },
  {
    id: 'rate_limit_status',
    category: 'Rate Limiting',
    name: 'Rate Limit Status',
    description: 'Status for a specific identifier',
    method: 'GET',
    path: '/rate-limit/status/{identifier}',
    kind: 'http',
    bodyMode: 'none',
    defaultPathParams: { identifier: 'session:session_demo' },
  },
  {
    id: 'rate_limit_reset',
    category: 'Rate Limiting',
    name: 'Rate Limit Reset',
    description: 'Reset limiter state for identifier',
    method: 'POST',
    path: '/rate-limit/reset/{identifier}',
    kind: 'http',
    bodyMode: 'none',
    defaultPathParams: { identifier: 'session:session_demo' },
  },
  {
    id: 'rate_limit_health',
    category: 'Rate Limiting',
    name: 'Rate Limit Health',
    description: 'Rate limit infrastructure health status',
    method: 'GET',
    path: '/rate-limit/health',
    kind: 'http',
    bodyMode: 'none',
  },
  {
    id: 'rate_limit_config',
    category: 'Rate Limiting',
    name: 'Rate Limit Config',
    description: 'Resolved limiter configuration',
    method: 'GET',
    path: '/rate-limit/config',
    kind: 'http',
    bodyMode: 'none',
  },

  {
    id: 'graphql',
    category: 'GraphQL',
    name: 'GraphQL Query',
    description: 'GraphQL endpoint for schema/data introspection',
    method: 'POST',
    path: '/graphql',
    kind: 'http',
    bodyMode: 'json',
    defaultBody: {
      query: 'query { __typename }',
    },
  },
]

export const METHOD_STYLE: Record<HttpMethod, string> = {
  GET: 'method-get',
  POST: 'method-post',
  PUT: 'method-put',
  PATCH: 'method-patch',
  DELETE: 'method-delete',
}

export const CATEGORY_GROUPS = {
  operations: ['Health', 'Evaluation', 'Rate Limiting', 'GraphQL'],
  admin: ['Admin'],
  streams: ['Agent', 'Admin'],
  agent: ['Agent', 'Sessions', 'Models', 'Router'],
} as const
